const supabseUrl = "https://emnvyydctkavludfazpd.supabase.co";
const supabseAnonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtbnZ5eWRjdGthdmx1ZGZhenBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk4NDQ0NTksImV4cCI6MjA0NTQyMDQ1OX0.wzTJLxNCrUipZPgHu4upE4CU_uNGVKoWTHxG7yAeqZs";
